import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import type { PayRun, PayRunLine } from "@/types/database";

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: "#0e1a1a", fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 },
  biz: { fontSize: 16, fontWeight: 700 },
  title: { fontSize: 20, fontWeight: 700, color: "#0f766e" },
  sub: { color: "#5c6b6b", marginTop: 2 },
  section: { marginBottom: 16 },
  label: { fontSize: 8, textTransform: "uppercase", letterSpacing: 1, color: "#93a1a1", marginBottom: 3 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: "#e3e9e8" },
  rowTotal: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 7, borderTopWidth: 1.5, borderTopColor: "#0e1a1a", marginTop: 4 },
  bold: { fontWeight: 700 },
  muted: { color: "#5c6b6b" },
});

const money = (n: number) => `$${(Number(n) || 0).toLocaleString("en-AU", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (d: string) => new Date(d).toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" });

export function PayslipDocument({ line, run, businessName }: { line: PayRunLine; run: PayRun; businessName: string }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.biz}>{businessName}</Text>
            <Text style={s.sub}>Payslip</Text>
          </View>
          <Text style={s.title}>PAYSLIP</Text>
        </View>

        <View style={[s.section, { flexDirection: "row", justifyContent: "space-between" }]}>
          <View>
            <Text style={s.label}>Employee</Text>
            <Text style={s.bold}>{line.name}</Text>
          </View>
          <View>
            <Text style={s.label}>Pay period</Text>
            <Text>{date(run.period_start)} – {date(run.period_end)}</Text>
          </View>
          <View>
            <Text style={s.label}>Pay date</Text>
            <Text>{date(run.pay_date)}</Text>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.label}>Earnings</Text>
          <View style={s.row}>
            <Text>{line.pay_type === "hourly" ? `Ordinary hours (${line.hours} × ${money(line.rate)})` : "Salary"}</Text>
            <Text>{money(line.gross)}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.muted}>Tax withheld (PAYG)</Text>
            <Text style={s.muted}>- {money(line.tax_amount)}</Text>
          </View>
          <View style={s.rowTotal}>
            <Text style={s.bold}>Net pay</Text>
            <Text style={s.bold}>{money(line.net)}</Text>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.label}>Superannuation (employer contribution)</Text>
          <View style={s.row}>
            <Text style={s.muted}>Super guarantee</Text>
            <Text style={s.muted}>{money(line.super_amount)}</Text>
          </View>
        </View>

        <Text style={[s.muted, { fontSize: 8, marginTop: 20 }]}>
          Generated by {businessName}. This payslip is a record of pay for the period shown.
        </Text>
      </Page>
    </Document>
  );
}
