/**
 * Lucide → Phosphor compat layer.
 * Re-exports every Lucide icon name in use, mapped to the closest Phosphor icon.
 * Phosphor weight defaults to "regular" via IconContext in layout.tsx.
 */
import type { Icon } from "@phosphor-icons/react";

export {
  // Direct name matches
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  Brain,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Eye,
  FileText,
  GitBranch,
  Hammer,
  Info,
  Image,
  Key,
  MapPin,
  Moon,
  Newspaper,
  Package,
  Palette,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Receipt,
  Repeat,
  Shield,
  ShieldCheck,
  Square,
  Star,
  Sun,
  User,
  UserPlus,
  Users,
  Wrench,
  X,
  XCircle,
} from "@phosphor-icons/react";

export {
  // Renames — Lucide name → Phosphor equivalent
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Warning as TriangleAlert,
  BellRinging as BellRing,
  Robot as Bot,
  Stack as Boxes,
  Buildings as Building2,
  CalendarDots as CalendarDays,
  CheckCircle as CheckCircle2,
  CheckCircle as CircleCheck,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUp,
  CaretUpDown as ChevronsUpDown,
  ClipboardText as ClipboardList,
  Clipboard as ClipboardPaste,
  Columns as Columns3,
  CurrencyDollar as DollarSign,
  DownloadSimple as Download,
  PencilSimple as Edit,
  PencilSimple as Edit2,
  ArrowSquareOut as ExternalLink,
  EyeSlash as EyeOff,
  File as FileCheck,
  FileText as FileClock,
  FileArrowDown as FileDown,
  Files as FileStack,
  Funnel as Filter,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  House as Home,
  Image as ImageIcon,
  ImageSquare as ImagePlus,
  Key as KeyRound,
  SquaresFour as LayoutDashboard,
  SquaresFour as LayoutGrid,
  LinkSimple as Link2,
  LinkBreak as Link2Off,
  CircleNotch as Loader2,
  CircleNotch as LoaderCircle,
  SignOut as LogOut,
  Envelope as Mail,
  EnvelopeOpen as MailCheck,
  EnvelopeSimpleOpen as MailSearch,
  List as Menu,
  ChatCircle as MessageSquare,
  Microphone as Mic,
  ArrowsIn as Minimize2,
  DotsThree as MoreHorizontal,
  CursorClick as MousePointer2,
  ArrowsOutCardinal as Move,
  NavigationArrow as Navigation,
  XCircle as OctagonX,
  Sidebar as PanelLeft,
  PencilLine as PenLine,
  Plug as PlugZap,
  ArrowClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  GearSix as Settings2,
  ShareNetwork as Share2,
  Sparkle as Sparkles,
  NoteBlank as StickyNote,
  Table as TableProperties,
  Trash as Trash2,
  TrendUp as TrendingUp,
  UploadSimple as Upload,
  UserCircleCheck as UserCheck,
  UserCircle as UserCircle2,
  UserCircleCheck as UserRoundCheck,
  UsersThree as Users2,
  WebhooksLogo as Webhook,
  FlowArrow as Workflow,
  Lightning as Zap,
} from "@phosphor-icons/react";

// Compat type for code that imports `LucideIcon`
export type LucideIcon = Icon;
