"use client";

/**
 * App icon set — clean Lucide line icons, re-exported under the names the app
 * uses. A few brand marks (GitHub / Google / node-graph) come from Phosphor,
 * which has dedicated glyphs for them. Import icons from here, never from the
 * libraries directly, so the whole app can be re-themed in one place.
 */
import type { LucideIcon } from "lucide-react";

// Brand / specialty marks kept from Phosphor.
export { GithubLogo, GoogleLogo, Graph } from "@phosphor-icons/react";

export {
  // Names identical to Lucide
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  Brain,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  Circle,
  CircleCheck,
  Clock,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Globe,
  Plug,
  Target,
  Eye,
  Lock,
  FileText,
  GitBranch,
  Hammer,
  Info,
  Image,
  Key,
  MapPin,
  Moon,
  Newspaper,
  Package,
  Paperclip,
  Palette,
  Pause,
  Pencil,
  Phone,
  PhoneOff,
  Play,
  Plus,
  Receipt,
  Repeat,
  Shield,
  ShieldCheck,
  Square,
  Star,
  Sun,
  User,
  UserPlus,
  Users,
  Wrench,
  X,
  BellRing,
  Bot,
  Boxes,
  Building2,
  CalendarDays,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  ChevronUp,
  ChevronsUpDown,
  ClipboardList,
  ClipboardPaste,
  Columns3,
  DollarSign,
  Download,
  ExternalLink,
  EyeOff,
  FileCheck,
  FileClock,
  FileDown,
  FileStack,
  Filter,
  History,
  Home,
  ImagePlus,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  Link2Off,
  LoaderCircle,
  LogOut,
  Mail,
  MailCheck,
  MailSearch,
  Menu,
  MessageSquare,
  Mic,
  Minimize2,
  Move,
  Maximize2,
  GripVertical,
  ListChecks,
  Navigation,
  OctagonX,
  PanelLeft,
  PenLine,
  PlugZap,
  Activity,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  Share2,
  Sparkles,
  StickyNote,
  TableProperties,
  Trash2,
  TrendingUp,
  Upload,
  UserCheck,
  UserRoundCheck,
  Webhook,
  Workflow,
  Zap,
  Volume2,
  VolumeX,
  Megaphone,
  // Aliases — app name ← current Lucide name
  CircleAlert as AlertCircle,
  TriangleAlert as AlertTriangle,
  TriangleAlert,
  CircleCheck as CheckCircle,
  CircleCheck as CheckCircle2,
  CircleHelp as HelpCircle,
  CircleX as XCircle,
  SquarePen as Edit,
  SquarePen as Edit2,
  Ellipsis as MoreHorizontal,
  MousePointer as MousePointer2,
  LoaderCircle as Loader2,
  Image as ImageIcon,
  Code as CodeIcon,
  CircleUser as UserCircle2,
  UsersRound as Users2,
} from "lucide-react";

// Compat type for code that imports `LucideIcon`.
export type { LucideIcon };
